# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 10000
        min-spare-threads: 30
    #context-path: /shuiwu
    port: 8080
# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: test
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss"
        time-zone: "GMT+8"
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 2
        host: 123.123.123.31
        port: 6379
        password: 123      # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-idle: 1000
                max-wait:
                min-idle: 5
    servlet:
        multipart:
            max-file-size: 1001MB
            max-request-size: 1001MB
            enabled: true
    devtools:
        livereload:
            enabled: false
logging:
    level:
        io.zt.modules: DEBUG
    config: classpath:logback-boot.xml
file:
  path: file:/opt/server/files/
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

